name: chalk
description: Chalk helps to style your terminal strings
version: 1.0.3
homepage: https://github.com/shan-shaji/chalkdart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0

dependencies: 
